packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@convex-dev/auth': ^0.0.81
  '@tanstack/react-query': ^5.90.2
  convex: 1.27.4
  eslint: ^9.35.0
  lucide-react: 0.539.0
  prettier: ^3.6.2
  react-querybuilder: ^8.8.3
  tailwindcss: ^4.1.12
  typescript: ^5.9.3
  zod: 3.25.76
  zustand: ^5.0.7

catalogs:
  react19:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    react: 19.2.0
    react-dom: 19.2.0

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - sharp

overrides:
  '@codemirror/language': 6.11.2
  '@codemirror/view': 6.38.1
  '@types/minimatch': 5.1.2
  zod: 3.25.76
